#pragma once

#define BRAINFUCK_INCREMENT_POINTER '>'
#define BRAINFUCK_DECREMENT_POINTER '<'
#define BRAINFUCK_INCREMENT_MEMORY '+'
#define BRAINFUCK_DECREMENT_MEMORY '-'
#define BRAINFUCK_LEFT_PARENTHESES '['
#define BRAINFUCK_RIGHT_PARENTHESES ']'
#define BRAINFUCK_OUTPUT '.'
#define BRAINFUCK_INPUT ','
